### ISSUE TITLE
Problems with Button.h

### ISSUE THREAD

**Issue by psander247** [mikaelpatel/Arduino-GPIO#15]
Hello, 
first of all: Thank you for the great work. 
This makes programming so much easier and more efficient.

I have a problem with the button class. I tried to turn on the board led by pressing a button and turning it off when releasing. 
The led stays on all the time... 

#include "GPIO.h"
#include "Button.h"

GPIO<BOARD::D13> led;
Button<BOARD::D5> button;

void setup()
{
  led.output();
}

void loop()
{
   if(button) {
    led=1;
   }
   else
   {
    led=0;
   }
 
}

**Comment by mikaelpatel** [comment]
@psander247 Sorry for the very slow response. I hope you have already found the issue. In any case, if you study the example sketch, https://github.com/mikaelpatel/Arduino-GPIO/blob/master/examples/Button/Button.ino, the Button class is used with the member function, ischanged(), https://github.com/mikaelpatel/Arduino-GPIO/blob/master/src/Button.h#L50. This samples the buttton state and checks for any change. Using the Button instance directly as in your example above will only sample the button pin and that will be always high as the pin is in pull-up mode. 

More in the doc-page, https://mikaelpatel.github.io/Arduino-GPIO/

Cheers and keep safe, Mikael.
