### ISSUE TITLE
Hardware/AVR/GPIO toggle() function incorrect assignment?

### ISSUE THREAD

**Issue by GreyLimit** [mikaelpatel/Arduino-GPIO#17]
The definition of the "toggle()" function in the file "Hardware/AVR/GPIO.h" uses the "|=" assignment .. shouldn't it use "^=" to achieve the actual "toggle" effect?

**Comment by mikaelpatel** [comment]
Sorry for the late reply. This is a great question and the suggested solution is also valid. 

The toggle() function is actually highly optimized for the AVR GPIO hardware. Writing to the PIN register will toggle the corresponding pin. On most AVR MCUs this is done in a single clock cycle. 

Using XOR assumes reading the PORT register which does take considerately more clock cycles. I should add that the AVR GCC compiler might be able to detect this and replace it with writing the PIN register. But I would not count on it.  

Last but not lease, the toggle operation needs to be atomic which is not guaranteed when using several instructions. Toggling by using a bit set/clear instruction is atomic.
