### ISSUE TITLE
Not working with bad stepper drivers TB67S109AFTG

### ISSUE THREAD

**Issue by BeeMeeMan** [mikaelpatel/Arduino-GPIO#18]
Hey! Use your library for my project, and all works fine with different stepper drivers.
Now with TB67S109AFTG  nothing works.

When I add default code with DigitalWhrite all works. And with this library not. Seems like pin not make fully 0v of 5v and this drivers are sensitive for this. 

For my old drivers declare pin types in init was ok:
 StepMotor() {
      stepPin.output();
      dirPin.output();
      enPin.output();
    }

And for this one I must declare them in setup with pinMode:
 pinMode (4, OUTPUT);
 pinMode (5, OUTPUT);
 pinMode (6, OUTPUT);

Then they work, but really badly: hold torque in half power, can don't listen for dir pin etc.

Attach my code:

// StepMotor.h
#ifndef StepMotor_h
#define StepMotor_h

#include "GPIO.h"

template<BOARD::pin_t STEP_PIN, BOARD::pin_t DIR_PIN, BOARD::pin_t EN_PIN>
class StepMotor {
  public:
   StepMotor() {
      stepPin.output();
      dirPin.output();
      enPin.output();
    }

    void runForward(int stepInterval, int dis) {
      runMotor(LOW, stepInterval, dis);
    }
    
    void runBack(int stepInterval, int dis){
       runMotor(HIGH, stepInterval, dis);
    }

     void runForeverWithAcceleration(bool dir, int startStepInterval, int endStepInterval) {
     enPin = LOW;
     dirPin = dir;

     if (currentInterval == 0) {
     currentInterval = startStepInterval;
     }

      if (micros() - previousMillis >= currentInterval) {
        stepPin.toggle();
        
        if (endStepInterval <= currentInterval){
          currentInterval -= 20;
        }
        
        previousMillis = micros();
      }
    }

    void resetCurrentInterval() {
      currentInterval = 0;
    }

    void runForever(bool dir, int stepInterval) {
     enPin = LOW;
     dirPin = dir;

       if (micros() - previousMillis >= stepInterval) {
        stepPin.toggle();
        previousMillis = micros();
      }
    }

    void setCurrentDisToZero() {
      currentDis = 0;
    }

    void setCurrentDisToMax() {
      currentDis = 31000;
    }

    void setCurrentDis(int value) {
      currentDis = value;
    }

     void activate(bool value = LOW) {
      enPin = value;
    }

     void deactivate() {
      enPin = HIGH;
    }

    int getCurrentDis(){
      return currentDis;
    }

    bool isRunToDis(int dis){
      return currentDis >= dis;
    }
    
  private:
  unsigned long previousMillis = 0;
  int currentDis = 0;
  int currentInterval = 0;

  void runMotor(bool dir, int stepInterval, int dis) {
     enPin = LOW;
     dirPin = dir;

      if (micros() - previousMillis >= stepInterval && currentDis < dis) {
        stepPin.toggle();
    
        ++currentDis;
        previousMillis = micros();
      }
    }
   
  protected:
    GPIO<STEP_PIN> stepPin;
    GPIO<DIR_PIN> dirPin;
    GPIO<EN_PIN> enPin;
};

#endif

**Comment by mikaelpatel** [comment]
@BeeMeeMan Thanks for your interest in this library. Are you reporting an error or asking for help debugging your code?

**Comment by BeeMeeMan** [comment]
> @BeeMeeMan Thanks for your interest in this library. Are you reporting an error or asking for help debugging your code?

Hey! Thanks for answer!. It is a really good library, thanks for it. It is greatly expands the capabilities of 16MHz. However, pin low/hight of this lib  is different from DigitalRead/Write. I rewrote this code with DigitaWrite and all works fine. I wonder if I am doing something wrong with this library(not add some parameter somewhere) or this is the price we pay for speed, or there is a bug, witch can be fixed. Issue is that the output signal on pin with this library is different from basic DigitaWrite, and some sensitive equipment may see that difference, as in my case drivers not working.

**Comment by mikaelpatel** [comment]
@BeeMeeMan You need to add more info if you want help. What do you think could be useful? You are only guessing right now. And unfortunately mostly wrong. I would start by verifying that there are no symbol conflicts. The driver code might contain symbols that replace pin symbols and therefore you code uses the wrong pins. Cheers Mikael. 
PS have you measured the voltage on the pins. You might have broken your board.

**Comment by BeeMeeMan** [comment]
Thanks, idea with wrong pin maybe can be good. I'll try to check it.
